"""Mock data for the EuroStartup Radar application."""
import pandas as pd

MOCK_CITIES = [
    {
        "id": "1",
        "name": "London",
        "country": "UK",
        "countryCode": "GB",
        "region": "Western Europe",
        "votes": 45000,
        "attractivenessIndex": 92,
        "status": "established",
        "sectors": {"Fintech": 120, "Edtech": 45, "Healthtech": 30, "SaaS": 80, "Deeptech": 20},
        "funding": 12500,
        "lat": 51.5074,
        "lng": -0.1278,
    },
    {
        "id": "2",
        "name": "Berlin",
        "country": "Germany",
        "countryCode": "DE",
        "region": "DACH",
        "votes": 38000,
        "attractivenessIndex": 84,
        "status": "established",
        "sectors": {"Fintech": 80, "Edtech": 30, "Healthtech": 40, "SaaS": 90, "Deeptech": 25},
        "funding": 8400,
        "lat": 52.52,
        "lng": 13.405,
    },
    {
        "id": "15",
        "name": "Cologne",
        "country": "Germany",
        "countryCode": "DE",
        "region": "DACH",
        "votes": 12000,
        "attractivenessIndex": 68,
        "status": "rising",
        "sectors": {"Fintech": 30, "Edtech": 15, "Healthtech": 25, "SaaS": 40, "Deeptech": 15},
        "funding": 1200,
        "lat": 50.9375,
        "lng": 6.9603,
    },
    {
        "id": "16",
        "name": "Frankfurt",
        "country": "Germany",
        "countryCode": "DE",
        "region": "DACH",
        "votes": 25000,
        "attractivenessIndex": 79,
        "status": "established",
        "sectors": {"Fintech": 95, "Edtech": 10, "Healthtech": 15, "SaaS": 50, "Deeptech": 20},
        "funding": 4500,
        "lat": 50.1109,
        "lng": 8.6821,
    },
    {
        "id": "3",
        "name": "Paris",
        "country": "France",
        "countryCode": "FR",
        "region": "Western Europe",
        "votes": 35000,
        "attractivenessIndex": 78,
        "status": "established",
        "sectors": {"Fintech": 70, "Edtech": 25, "Healthtech": 50, "SaaS": 60, "Deeptech": 35},
        "funding": 9800,
        "lat": 48.8566,
        "lng": 2.3522,
    },
    {
        "id": "4",
        "name": "Tallinn",
        "country": "Estonia",
        "countryCode": "EE",
        "region": "Nordics",
        "votes": 12000,
        "attractivenessIndex": 71,
        "status": "rising",
        "sectors": {"Fintech": 40, "Edtech": 15, "Healthtech": 10, "SaaS": 50, "Deeptech": 10},
        "funding": 850,
        "lat": 59.437,
        "lng": 24.7536,
    },
    {
        "id": "5",
        "name": "Warsaw",
        "country": "Poland",
        "countryCode": "PL",
        "region": "CEE",
        "votes": 15000,
        "attractivenessIndex": 68,
        "status": "rising",
        "sectors": {"Fintech": 30, "Edtech": 20, "Healthtech": 15, "SaaS": 40, "Deeptech": 15},
        "funding": 1100,
        "lat": 52.2297,
        "lng": 21.0122,
    },
    {
        "id": "6",
        "name": "Lisbon",
        "country": "Portugal",
        "countryCode": "PT",
        "region": "Western Europe",
        "votes": 14000,
        "attractivenessIndex": 63,
        "status": "hidden gem",
        "sectors": {"Fintech": 25, "Edtech": 10, "Healthtech": 20, "SaaS": 30, "Deeptech": 5},
        "funding": 950,
        "lat": 38.7223,
        "lng": -9.1393,
    },
    {
        "id": "7",
        "name": "Krakow",
        "country": "Poland",
        "countryCode": "PL",
        "region": "CEE",
        "votes": 8000,
        "attractivenessIndex": 65,
        "status": "undervalued",
        "sectors": {"Fintech": 15, "Edtech": 10, "Healthtech": 10, "SaaS": 25, "Deeptech": 10},
        "funding": 450,
        "lat": 50.0647,
        "lng": 19.9450,
    },
    {
        "id": "8",
        "name": "Munich",
        "country": "Germany",
        "countryCode": "DE",
        "region": "DACH",
        "votes": 22000,
        "attractivenessIndex": 82,
        "status": "established",
        "sectors": {"Fintech": 40, "Edtech": 15, "Healthtech": 35, "SaaS": 50, "Deeptech": 40},
        "funding": 5200,
        "lat": 48.1351,
        "lng": 11.5820,
    },
    {
        "id": "9",
        "name": "Hamburg",
        "country": "Germany",
        "countryCode": "DE",
        "region": "DACH",
        "votes": 18000,
        "attractivenessIndex": 75,
        "status": "established",
        "sectors": {"Fintech": 30, "Edtech": 10, "Healthtech": 20, "SaaS": 45, "Deeptech": 15},
        "funding": 2800,
        "lat": 53.5511,
        "lng": 9.9937,
    },
    {
        "id": "10",
        "name": "Stockholm",
        "country": "Sweden",
        "countryCode": "SE",
        "region": "Nordics",
        "votes": 28000,
        "attractivenessIndex": 88,
        "status": "established",
        "sectors": {"Fintech": 60, "Edtech": 20, "Healthtech": 25, "SaaS": 70, "Deeptech": 20},
        "funding": 4100,
        "lat": 59.3293,
        "lng": 18.0686,
    },
    {
        "id": "11",
        "name": "Helsinki",
        "country": "Finland",
        "countryCode": "FI",
        "region": "Nordics",
        "votes": 15000,
        "attractivenessIndex": 79,
        "status": "rising",
        "sectors": {"Fintech": 30, "Edtech": 15, "Healthtech": 20, "SaaS": 40, "Deeptech": 25},
        "funding": 1800,
        "lat": 60.1699,
        "lng": 24.9384,
    },
    {
        "id": "12",
        "name": "Prague",
        "country": "Czech Republic",
        "countryCode": "CZ",
        "region": "CEE",
        "votes": 11000,
        "attractivenessIndex": 67,
        "status": "rising",
        "sectors": {"Fintech": 20, "Edtech": 10, "Healthtech": 10, "SaaS": 35, "Deeptech": 10},
        "funding": 750,
        "lat": 50.0755,
        "lng": 14.4378,
    },
    {
        "id": "13",
        "name": "Vienna",
        "country": "Austria",
        "countryCode": "AT",
        "region": "DACH",
        "votes": 14000,
        "attractivenessIndex": 72,
        "status": "rising",
        "sectors": {"Fintech": 25, "Edtech": 15, "Healthtech": 20, "SaaS": 30, "Deeptech": 10},
        "funding": 1400,
        "lat": 48.2082,
        "lng": 16.3738,
    },
    {
        "id": "14",
        "name": "Amsterdam",
        "country": "Netherlands",
        "countryCode": "NL",
        "region": "Western Europe",
        "votes": 26000,
        "attractivenessIndex": 85,
        "status": "established",
        "sectors": {"Fintech": 55, "Edtech": 20, "Healthtech": 25, "SaaS": 60, "Deeptech": 15},
        "funding": 3900,
        "lat": 52.3702,
        "lng": 4.8952,
    },
    {
        "id": "17",
        "name": "Lyon",
        "country": "France",
        "countryCode": "FR",
        "region": "Western Europe",
        "votes": 12000,
        "attractivenessIndex": 65,
        "status": "rising",
        "sectors": {"Fintech": 20, "Edtech": 15, "Healthtech": 35, "SaaS": 30, "Deeptech": 15},
        "funding": 1100,
        "lat": 45.7640,
        "lng": 4.8357,
    },
    {
        "id": "18",
        "name": "Manchester",
        "country": "UK",
        "countryCode": "GB",
        "region": "Western Europe",
        "votes": 18000,
        "attractivenessIndex": 72,
        "status": "established",
        "sectors": {"Fintech": 45, "Edtech": 20, "Healthtech": 15, "SaaS": 40, "Deeptech": 10},
        "funding": 2200,
        "lat": 53.4808,
        "lng": -2.2426,
    },
    {
        "id": "19",
        "name": "Rotterdam",
        "country": "Netherlands",
        "countryCode": "NL",
        "region": "Western Europe",
        "votes": 11000,
        "attractivenessIndex": 64,
        "status": "rising",
        "sectors": {"Fintech": 25, "Edtech": 10, "Healthtech": 15, "SaaS": 30, "Deeptech": 20},
        "funding": 950,
        "lat": 51.9225,
        "lng": 4.4792,
    },
    {
        "id": "20",
        "name": "Barcelona",
        "country": "Spain",
        "countryCode": "ES",
        "region": "Western Europe",
        "votes": 24000,
        "attractivenessIndex": 81,
        "status": "established",
        "sectors": {"Fintech": 50, "Edtech": 25, "Healthtech": 30, "SaaS": 55, "Deeptech": 15},
        "funding": 3200,
        "lat": 41.3874,
        "lng": 2.1686,
    },
    {
        "id": "21",
        "name": "Madrid",
        "country": "Spain",
        "countryCode": "ES",
        "region": "Western Europe",
        "votes": 21000,
        "attractivenessIndex": 78,
        "status": "established",
        "sectors": {"Fintech": 60, "Edtech": 15, "Healthtech": 20, "SaaS": 45, "Deeptech": 10},
        "funding": 2800,
        "lat": 40.4168,
        "lng": -3.7038,
    },
]

def get_cities_dataframe():
    """Load cities data into a pandas DataFrame."""
    return pd.DataFrame(MOCK_CITIES)

def get_regions():
    """Get unique regions."""
    return sorted(set(city["region"] for city in MOCK_CITIES))

def get_sectors():
    """Get all available sectors."""
    sectors = set()
    for city in MOCK_CITIES:
        sectors.update(city["sectors"].keys())
    return sorted(sectors)

def get_statuses():
    """Get all available status types."""
    return sorted(set(city["status"] for city in MOCK_CITIES))
